# Generated by Django 4.2.15 on 2025-12-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("account_executive", "Account Executive"),
                    ("teller", "Teller"),
                    ("branch_manager", "Branch Manager"),
                ],
                default="customer",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
